area: se3-stockholm  # {'se1-lulea', se2-sundsvall, se3-stockholm, se4-malmo}
price_threshold: 40  # öre/kWh
address: 'localhost'  # Socket address
port: 36330  # Socket port
config_file: '/etc/fahclient/config.xml' # Include slots from config file
slots:  # Include slots explicitly
    - 0
    - 1
encoding: 'utf-8'  # Message encoding